CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID INT auto_increment PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    PRICE DOUBLE(10, 2) NOT NULL,
    QUANTITY INT NOT NULL,
);